export class Offer {
    id:number
    ContactId:string
    ProjectId:string
    ProjectAddress:string
    UnitId:string
    Direction:string
    FloorNo:number
    FloorArea:number
    HandOverTime:Date
    RatePerSft:number
    UnitCost:number
    ParkingCost:number
    TotalCost:number
    BookingMoney:number
    BookingDate:Date
    DownPayment:number
    DownPaymentDate:Date
    InstallpaymentType:string
    NoOfInstallpayment:number
    AmountPerInstallment:number
    Additioncost:number
    ReserveFund:number
    UtilityConnectionCost:number
    RegistrationCost:number
    OthersCost:number
    issueby:string
    VisibleStatus:number
    createdAt:Date
    updatedAt:Date
  }