export class Sales {
    id:number
    ProjectId:string
    ProjectAddress:string
    UnitId:string
    Direction:string
    FloorNo:number
    FloorArea:number
    HandOverTime:Date
    RatePerSft:number
    UnitCost:number
    ParkingCost:number
    TotalCost:number
    BookingMoney:number
    DownPayment:number
    DownPaymentDate:Date
    InstallmentType:string
    NoOfInstallment:number
    AmountPerInstallment:number
    ContactId:string
    MobileNo:string
    Email:string
    FatherName:string
    MotherName:string
    PresetAddress:string
    PermanentAddress:string
    Nationality:string
    NationalId:string
    issueby:string
    VisibleStatus:number

    SLNo:number
    Particular:string
    Amount:number
    ScheduleDate:Date
  }